Repository AY2425S1-CS2103T-F11-4/tp, pull requests merged in 2024-10, with the labels that each got.

#28 Add Wen Xuan's photo
  docs/images/e1121208.png
Labels: priority.High

#22 Add Sean's photo
  docs/images/seandias.png
Labels: priority.High

#24 Add Muhammad's photo
  docs/images/muhdbhz.png
Labels: priority.High

#19 Add Rongyi's photo
  docs/AboutUs.md
  docs/images/lrongyi.png
Labels: priority.High

#30 Update AboutUs.md
  docs/AboutUs.md
Labels: priority.High

#31 Update AboutUs.md
  docs/AboutUs.md
Labels: priority.High

#52 Fix checkstyle errors
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#58 Feature: List All Client Profiles
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#61 Create AddPropertyCommand class
  src/main/java/seedu/address/logic/commands/AddClientProfile.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddClientParser.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#63 Merge Upstream Master
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
Labels: priority.Low

#64 Fix checkstyle errors
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddClientProfile.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddClientParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteClientProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientProfileParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteClientProfileCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore

#75 Fix README not linking to product website
  README.md
  docs/index.md
Labels: priority.High

#76 AppointmentCommand bug fix
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
Labels: type.Bug

#79 Create tests for Property, AddPropertyCommand and Index
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/model/person/PropertyTest.java
Labels: priority.High

#78 Rework DeleteClientProfileCommandTest
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#82 Rework delete client profile command test
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#83 Update documentation
  docs/UserGuide.md
  docs/assets/css/UserGuide.css
  docs/index.md
Labels: priority.High

#91 Improve CLI
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
Labels: priority.Medium

#93 Developer guide updated with table
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/_includes/toc.html
Labels: type.Chore

#87 Resolve issues with LogicManagerTest
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#92 Improve CLI further, update ListCommand to accommodate for empty list and add more tests in LogicMangerTest
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
Labels: priority.Medium

#95 Resolving Checkstyle Errors for improveCLI branch
  docs/UserGuide.md
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Chore

#98 Improve cli
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
Labels: priority.Medium

#99 Resolve checkstyle issues
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#102 Update build.gradle
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/ui/PersonCardUiTest.java
Labels: type.Bug

#104 Fix bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddClientProfile.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddClientParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientProfileParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#103 Feature: Delete Property
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyCommandParser.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyCommandParserTest.java
Labels: priority.High

#106 Resolve checkstyle errors and debug test failures
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientProfileParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#108 Fix result display for AddClientProfile
  src/main/java/seedu/address/logic/commands/AddClientProfile.java
Labels: priority.High

#118 Improve UI, CLI messages and implement Help Chat Bot
  build.gradle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddClientProfile.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/ChatWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/ChatWindow.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#120 Add tests for ChatWindow
  build.gradle
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/ui/ChatWindowTest.java
Labels: priority.High

#124 Ui: Change the look of tags
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#123 Attempt fix for ubuntu endless loading
  build.gradle
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
Labels: priority.High

#128 Change the UI of PersonCard
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/ui/PersonCardUiTest.java
Labels: priority.Medium

#131 Enable assertions
  build.gradle
Labels: priority.High

#134 Improve chat window
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
Labels: priority.High

#136 Create RoleTest
  src/test/java/seedu/address/model/person/RoleTest.java
Labels: priority.High

#137 Edit BetterModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Chore

#139 Edit ModelClassDiagram.puml to include Buyer/Seller classes
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Chore

#138 Edit UiClassDiagram.puml to include ChatWindow
  docs/diagrams/UiClassDiagram.puml
Labels: type.Chore

#135 Feature: Listing
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/ShowListingCommand.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Listings.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyListings.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/listing/Address.java
  src/main/java/seedu/address/model/listing/Area.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/listing/Price.java
  src/main/java/seedu/address/model/listing/Region.java
  src/main/java/seedu/address/model/listing/UniqueListingList.java
  src/main/java/seedu/address/model/listing/exceptions/DuplicateListingException.java
  src/main/java/seedu/address/model/listing/exceptions/ListingNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonListingsStorage.java
  src/main/java/seedu/address/storage/JsonSerializableListings.java
  src/main/java/seedu/address/storage/ListingStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/listing/AddressTest.java
  src/test/java/seedu/address/model/listing/AreaTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/listing/PriceTest.java
  src/test/java/seedu/address/model/listing/UniqueListingListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
Labels: priority.High

#141 Add Ui for ShowListings command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowListingCommand.java
  src/main/java/seedu/address/logic/commands/ShowListingsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/ChatWindow.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/ListingListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ListingListCard.fxml
  src/main/resources/view/ListingListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High

#115 Enforce Commit Script
  build.gradle
  hooks/commit-msg
  setup.sh
Labels: priority.Medium

#142 Update UML diagram to show Listing model
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Chore

#144 Documentation: Updated Class diagram for Storage class
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Chore

#143 Speed up the "Assistant is typing.." buffer
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
Labels: priority.Medium

#154 Create tests for AddListingCommand and ModelManager
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/listing/Area.java
  src/main/java/seedu/address/model/listing/Price.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/listing/AreaTest.java
  src/test/java/seedu/address/model/listing/PriceTest.java
  src/test/java/seedu/address/model/listing/RegionTest.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#166 Improve showListings UI + Bug Fixes
  src/main/java/seedu/address/model/listing/Region.java
  src/main/java/seedu/address/model/listing/UniqueListingList.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ListingListCard.fxml
  src/main/resources/view/ListingListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: priority.High

#168 Comment out ListingCardUiTest.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: alpha-bug

#169 Create MoreInfoCommand, MoreInfoWindow, MoreInfoController and respective classes for better useability
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/MoreInfoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MoreInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MoreInfoController.java
  src/main/java/seedu/address/ui/MoreInfoWindow.java
  src/main/resources/images/profile-picture.png
  src/main/resources/view/MoreInfoWindow.css
  src/main/resources/view/MoreInfoWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#170 Improve UI for ShowListings + Bug Fixes
  src/main/java/seedu/address/model/listing/Region.java
  src/main/java/seedu/address/model/listing/UniqueListingList.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ListingListCard.fxml
  src/main/resources/view/ListingListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: priority.High

#171 Listing features
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java
  src/main/java/seedu/address/logic/commands/ClearListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/EditListingCommand.java
  src/main/java/seedu/address/logic/commands/FindListingCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemoveBuyersFromListingCommand.java
  src/main/java/seedu/address/logic/commands/ShowListingsCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyersToListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java
  src/main/java/seedu/address/logic/parser/EditListingCommandParser.java
  src/main/java/seedu/address/logic/parser/FindListingsCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingParser.java
  src/main/java/seedu/address/logic/parser/RemoveBuyersFromListingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/ListingContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
Labels: priority.High

#176 Add CommandBoxUiTest, HelpWindowUiTest, MoreInfoCommandParserTest and MoreInfoControllerUiTest
  src/main/java/seedu/address/logic/commands/MoreInfoCommand.java
  src/main/resources/view/MoreInfoWindow.css
  src/test/java/seedu/address/logic/commands/MoreInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/MoreInfoCommandParserTest.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
  src/test/java/seedu/address/ui/HelpWindowUiTest.java
  src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
Labels: priority.High

#182 Merge testing-listingTests with master
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/listing/Area.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/listing/Price.java
  src/main/java/seedu/address/model/listing/Region.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonListingsStorageTest/invalidAndValidListings.json
  src/test/data/JsonListingsStorageTest/invalidListings.json
  src/test/data/JsonListingsStorageTest/notJsonFormatListings.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableListingsTest/duplicateListings.json
  src/test/data/JsonSerializableListingsTest/invalidListings.json
  src/test/data/JsonSerializableListingsTest/typicalListings.json
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/listing/AreaTest.java
  src/test/java/seedu/address/model/listing/PriceTest.java
  src/test/java/seedu/address/model/listing/RegionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedListingTest.java
  src/test/java/seedu/address/storage/JsonListingsStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableListingsTest.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#183 Add ShowListingsCommandTest and improve tests
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowListingsCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalListings.java
Labels: priority.High

#184 Add ListingContainsKeywordsPredicateTest
  src/test/java/seedu/address/model/listing/ListingContainsKeywordsPredicateTest.java
Labels: priority.High

#181 Add more tests
  src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/test/java/seedu/address/logic/commands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearListingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteListingCommandTest.java
  src/test/java/seedu/address/logic/commands/FindListingCommandTest.java
Labels: priority.High

#186 Change application logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ezstates32.jpg
  src/main/resources/images/ezstates_32.png
Labels: priority.Medium
