Repository AY2425S1-CS2103T-F11-4/tp, pull requests merged in 2024-11, with the labels that each got.

#185 Display buyers list in ListingCard
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/resources/view/ListingListCard.fxml
Labels: priority.High

#201 Testing: RemoveBuyersFromListingCommand
  src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java
  src/main/java/seedu/address/logic/commands/EditListingCommand.java
  src/main/java/seedu/address/logic/commands/MoreInfoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveBuyersFromListingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ezstates32.jpg
  src/main/resources/images/ezstates_32.png
  src/main/resources/view/ListingListCard.fxml
  src/test/java/seedu/address/logic/commands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearListingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditListingDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemoveBuyersFromListingCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
Labels: priority.High

#202 Testing listing tests
  src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java
  src/main/java/seedu/address/logic/commands/EditListingCommand.java
  src/main/java/seedu/address/logic/commands/MoreInfoCommand.java
  src/main/java/seedu/address/logic/commands/RemoveBuyersFromListingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/AddClientProfileTest.java
  src/test/java/seedu/address/logic/commands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearListingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteListingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditListingDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindListingCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveBuyersFromListingCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
Labels: priority.High

#205 Add more parser test and fix editListingCommandParser bug
  src/main/java/seedu/address/logic/parser/EditListingCommandParser.java
  src/test/java/seedu/address/logic/parser/AddBuyersToListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListingParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveBuyersFromListingCommandParserTest.java
Labels: priority.High

#206 Fix code mistakes
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#207 Add SampleDataUtilTest
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High

#215 Fix ListingCardUiTest and boost its coverage to 100%
  src/main/java/seedu/address/ui/ListingCard.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: priority.High, alpha-bug

#216 Fix bugs
  src/main/resources/view/MoreInfoWindow.fxml
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
  src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
Labels: priority.High

#217 Increase Code Coverage
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: type.Chore, priority.Medium

#220 Update ResultDisplay
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: priority.Medium

#223 Improve Chat Bot logic and add tests
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
Labels: priority.High

#224 Update HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/ui/HelpWindowUiTest.java
Labels: type.Enhancement, priority.Medium

#229 Remove `PREFIX_NAME` from parsers
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditListingCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyersToListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteClientProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditListingCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveBuyersFromListingCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddBuyersToListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteClientProfileCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListingParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveBuyersFromListingCommandParserTest.java
Labels: priority.Medium

#230 Pushing code coverage to the limit
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/ui/MainWindowUiTest.java
Labels: priority.High

#232 Add more test for code coverage
  src/test/java/seedu/address/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/MoreInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
Labels: priority.High

#247 Update user guide
  docs/UserGuide.md
  docs/images/ezstates_alt_picture.png
Labels: type.Chore

#248 Update user guide
  docs/UserGuide.md
  docs/images/appointments.png
  docs/images/appointments_old.png
  docs/images/help.png
  docs/images/moreinfo.png
  src/main/java/seedu/address/logic/commands/exceptions/img.png
Labels: type.Chore

#250 Feature: Clear Clients
  src/main/java/seedu/address/logic/commands/ClearClientCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/img.png
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearClientCommandTest.java
Labels: priority.Medium

#246 Create confirmation dialog
  src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/ui/ConfirmationDialog.java
  src/main/java/seedu/address/ui/ConfirmationDialogController.java
  src/main/resources/view/ConfirmationDialog.css
  src/main/resources/view/ConfirmationDialog.fxml
  src/test/java/seedu/address/logic/commands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/testutil/TypicalListings.java
  src/test/java/seedu/address/ui/ConfirmationDialogControllerUiTest.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
Labels: priority.High

#253 Bug Fix: Fix several listing commands not working
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High

#255 Update user guide and add tests
  docs/UserGuide.md
  docs/images/invalidInput.png
  docs/images/outputFromValidGoodbye.png
  docs/images/outputFromValidGreeting.png
  docs/images/outputFromValidQuery.png
  docs/images/outputOfInvalidInput.png
  docs/images/validGoodbye.png
  docs/images/validGreeting.png
  docs/images/validQuery.png
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ListingsTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/ui/UiManagerUiTest.java
Labels: type.Chore, priority.High

#256 Fix logic for EditListingCommand
  src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
Labels: priority.High, severity.High

#259 Improve code coverage
  docs/UserGuide.md
  docs/images/invalidInput.png
  docs/images/outputFromValidGoodbye.png
  docs/images/outputFromValidGreeting.png
  docs/images/outputFromValidQuery.png
  docs/images/outputOfInvalidInput.png
  docs/images/validGoodbye.png
  docs/images/validGreeting.png
  docs/images/validQuery.png
  src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java
  src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ListingsTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/FromTest.java
  src/test/java/seedu/address/model/appointment/ToTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
  src/test/java/seedu/address/ui/UiManagerUiTest.java
Labels: priority.High

#257 Bug fixes
  src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java
  src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/listing/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableListingsTest/duplicateListings.json
  src/test/java/seedu/address/logic/commands/listingcommands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/ListingsTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/FromTest.java
  src/test/java/seedu/address/model/appointment/ToTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/listing/PriceTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
Labels: priority.High, severity.High

#260 Fix PersonCard to accomodate worst case space complexity
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/ui/PersonCardUiTest.java
Labels: priority.High, severity.High, alpha-bug

#263 Ui: Fix hoverable empty list cells
  src/main/resources/view/Extensions.css
Labels: priority.High, alpha-bug

#262 Massive Bug Extermination
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/clientcommands/DeleteClientProfileCommand.java
  src/main/java/seedu/address/logic/commands/clientcommands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/Area.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/listing/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/clientcommands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/ClearListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ListingsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/listing/AreaTest.java
  src/test/java/seedu/address/model/listing/ListingContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: type.Bug, priority.High

#264 ListingCard: Fix Ui to accomodate malicious input + update tests
  src/main/java/seedu/address/ui/ListingCard.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
Labels: priority.High, severity.High, alpha-bug

#265 Pushing the limits with code coverage
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/clientcommandparsers/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/AddBuyersToListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/RemoveBuyersFromListingCommandParserTest.java
  src/test/java/seedu/address/ui/ListingListPanelUiTest.java
Labels: priority.High

#266 Add more tests
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
Labels: priority.High

#268 Add commands to ChatWindow.java.
  src/main/java/seedu/address/ui/ChatWindow.java
  src/test/java/seedu/address/ui/ChatWindowUiTest.java
Labels: priority.Low

#269 Place the final touches to the code coverage
  src/main/java/seedu/address/logic/Messages.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/FromTest.java
  src/test/java/seedu/address/model/appointment/ToTest.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
  src/test/java/seedu/address/ui/MainWindowUiTest.java
Labels: priority.High

#267 Fix Appointment Command
  src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/DeleteAppointmentCommandParser.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/EzstatesParserTest.java
  src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: severity.Medium

#275 Revert the Listing Commands back to using Index
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/listingcommands/AddBuyersToListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java
  src/main/java/seedu/address/logic/commands/listingcommands/RemoveBuyersFromListingCommand.java
  src/main/java/seedu/address/logic/parser/listingcommandparsers/AddBuyersToListingCommandParser.java
  src/main/java/seedu/address/logic/parser/listingcommandparsers/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/listingcommandparsers/DeleteListingCommandParser.java
  src/main/java/seedu/address/logic/parser/listingcommandparsers/EditListingCommandParser.java
  src/main/java/seedu/address/logic/parser/listingcommandparsers/RemoveBuyersFromListingCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/DeleteListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingDescriptorTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/RemoveBuyersFromListingCommandTest.java
  src/test/java/seedu/address/logic/parser/EzstatesParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/AddBuyersToListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/AddListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/DeletingListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/EditListingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/listingcommandparsers/RemoveBuyersFromListingCommandParserTest.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
Labels: priority.High

#404 Improve Code Quality for Tests
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/clientcommands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/DeleteClientProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/ShowClientsCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddBuyersToListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/AddListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/ClearListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/EditListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/FindListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/RemoveBuyersFromListingCommandTest.java
  src/test/java/seedu/address/logic/commands/listingcommands/ShowListingsCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/FromTest.java
  src/test/java/seedu/address/model/appointment/ToTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/listing/UniqueListingListTest.java
  src/test/java/seedu/address/model/person/HasAppointmentTodayPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalListings.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/CommandBoxUiTest.java
  src/test/java/seedu/address/ui/ConfirmationDialogUiTest.java
  src/test/java/seedu/address/ui/HelpWindowUiTest.java
  src/test/java/seedu/address/ui/ListingCardUiTest.java
  src/test/java/seedu/address/ui/MainUiTest.java
  src/test/java/seedu/address/ui/MainWindowUiTest.java
  src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
Labels: type.CodeQuality
